---
title: "Generalized Partial Least Squares"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This repository is for our work on generalized partial least squares. The preprint can be found here: [Beaton, D., ADNI, Saporta, G., Abdi, H. (2019). A generalization of partial least squares regression and correspondence analysis for categorical and mixed data: An application with the ADNI data. bioRxiv, 598888.](https://www.biorxiv.org/content/10.1101/598888v2).

The preprint was generated through RMarkdown with the `rticles` package, and is fully reproducible *for us* at least! You can reproduce it so long as you have access to ADNI data. Details forthcoming on data preparation and requirements. See the [Manuscript](/Manuscript/) directory for the manuscript's content and supplements (RMarkdown, PDF).

Other materials can be found in the [Code](/Code/) directory. The [IO](/IO/) (input/output) directory is currently empty.


The GPLS package lives in the [Package](/Package/) directory. It is documented and has a dependency on the GSVD package. Vignettes are forthcoming. See the [Package](/Package/) directory for installation instructions.
